MyShop/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using MyShop.Models;
using MyShop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyShop.Controllers
{
    public class ShopController : Controller
    {
        private readonly IShopRepository _shopRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly AppDbContext _appDbContext;



        public ShopController(IShopRepository shopRepository, ICategoryRepository categoryRepository, AppDbContext appDbContext)
        {
            _shopRepository = shopRepository;
            _categoryRepository = categoryRepository;
            _appDbContext = appDbContext;

        }

        //Returning as list//
      /*  public IActionResult List()
        {
            *//*  ViewBag.current = "Best seller";
              return View(_shopRepository.Getallproducts);*//*
            var shopListViewModel = new ShopListViewModel();
               shopListViewModel.Products = _shopRepository.Getallproducts;
               shopListViewModel.CurrentCategory = "Best sellers";
                return View(shopListViewModel);


        }
*/
        //For Dropdown view//
        public ViewResult List(string category)
        {
            IEnumerable<Shop> products;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                products = _shopRepository.Getallproducts.OrderBy(c => c.CategoryId);
                currentCategory = "All Products";
            }
            else
            {
                products = _shopRepository.Getallproducts.Where(c => c.Category.CategoryName == category);

                currentCategory = _categoryRepository.GetCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new ShopListViewModel
            {
                Products = products,
                CurrentCategory = currentCategory
            });
        }
        public IActionResult Details(int id)
        {
            var shop = _shopRepository.GetShopById(id);
            if (shop == null)
                return NotFound();
            return View(shop);

        }

        //Search products
        [HttpGet]
        public async Task<IActionResult> ProductSearch(string prdSearch)
        {
            ViewData["GetProducts"] = prdSearch;
            var prdQuery = from x in _appDbContext.Products select x;
            if (!String.IsNullOrEmpty(prdSearch))
            {
                prdQuery = prdQuery.Where(x => x.Name.Contains(prdSearch) || x.Description.Contains(prdSearch));
            }

            return View(new ShopListViewModel
                 {
                Products = prdQuery,
                CurrentCategory = ""
                  });
        }



    }
}

MyShop/Controllers/ShopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyShop.Models;

namespace MyShop.Controllers
{
    public class ShopsController : Controller
    {
        private readonly AppDbContext _context;

        public ShopsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Shops
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Products.Include(s => s.Category);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Shops/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Products
                .Include(s => s.Category)
                .FirstOrDefaultAsync(m => m.ShopId == id);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // GET: Shops/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Categoryid", "Categoryid");
            return View();
        }

        // POST: Shops/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ShopId,Name,Description,Price,ImageUrl,ImageThumbnailUrl,IsOnSale,OnStock,CategoryId")] Shop shop)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Categoryid", "Categoryid", shop.CategoryId);
            return View(shop);
        }

        // GET: Shops/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Products.FindAsync(id);
            if (shop == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Categoryid", "Categoryid", shop.CategoryId);
            return View(shop);
        }

        // POST: Shops/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ShopId,Name,Description,Price,ImageUrl,ImageThumbnailUrl,IsOnSale,OnStock,CategoryId")] Shop shop)
        {
            if (id != shop.ShopId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShopExists(shop.ShopId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Categoryid", "Categoryid", shop.CategoryId);
            return View(shop);
        }

        // GET: Shops/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Products
                .Include(s => s.Category)
                .FirstOrDefaultAsync(m => m.ShopId == id);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // POST: Shops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shop = await _context.Products.FindAsync(id);
            _context.Products.Remove(shop);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShopExists(int id)
        {
            return _context.Products.Any(e => e.ShopId == id);
        }
    }
}

MyShop/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/Slider/slide_4.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/Slider/slide_2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/Slider/slide_3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

MyShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">

   @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <link href="~/Contents/StyleSheet.css" rel="stylesheet" />*@

    <link href="~/Contents/StyleSheet.css" rel="stylesheet" />
    
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>







    <title>@ViewData["Title"] - MyShop</title>
</head>
<body>
    @*<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Shop" asp-action="List">All Products</a></li>
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>
            </div>
        </div>
    </nav>*@

    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Home Decor</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Shop" asp-action="List">My Shop<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    @await Component.InvokeAsync("CategoryMenu")
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Contact" asp-action="Index">Contact</a>
                </li>
                <li class="nav-item">
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </li>
                <partial name="_LoginPartial"/>
            </ul>

        </div>
    </nav>



    <div class="container">
        <div class=" row">
            <div class="col-sm-3">
                <p class="justify-content-xl-start">
                    <img class="img-responsive" src="~/Images/logo.png" />
                </p>
            </div>


        </div>
        <div class="col-md-12">
            @RenderBody()
        </div>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - MyShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

MyShop/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">

   @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <link href="~/Contents/StyleSheet.css" rel="stylesheet" />*@

    <link href="~/Contents/StyleSheet.css" rel="stylesheet" />
    
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>







    <title>@ViewData["Title"] Admin Page </title>
</head>
<body>
    @*<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Shop" asp-action="List">All Products</a></li>
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>
            </div>
        </div>
    </nav>*@

    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
        <a class="navbar-brand" asp-controller="Shops" asp-action="Create">Home Decor</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Shops" asp-action="Create">Createssssss<span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Shops" asp-action="Edit">Edit</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Shops" asp-action="Index"> Delete</a>
                </li>
                @*<li class="nav-item">
            @await Component.InvokeAsync("ShoppingCartSummary")
        </li>
        <partial name="_LoginPartial"/>*@
            </ul>

        </div>
    </nav>



    <div class="container">
        <div class=" row">
            <div class="col-sm-3">
                <p class="justify-content-xl-start">
                    <img class="img-responsive" src="~/Images/logo.png" />
                </p>
            </div>


        </div>
        <div class="col-md-12">
            @RenderBody()
        </div>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - MyShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

MyShop/Views/Shared/_productSearch.cshtml
<form id="searchForm" method="get" asp-action="ProductSearch">
    <p>
        <input id="searchForm" type="search" placeholder="search products" value="@ViewData["GetProducts"]" name="prdSearch" />
        <input type="submit" value="Search" class="btn btn-primary" />
    </p>
</form>

MyShop/Views/Shared/_shopCard.cshtml
@model Shop
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">

        <img src="@Model.ImageThumbnailUrl" alt="Imgae for the shop" />

        <div class="caption">
            <h3 class="pull-right"> @Model.Price.ToString("c")</h3>

            <h2> <a asp-controller="Shop" asp-action="Details" asp-route-id="@Model.ShopId"> @Model.Name </a></h2>

            <p> @Model.Description  </p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShoppingCart"
                   asp-route-ShopId="@Model.ShopId"> Add To Cart</a>
            </p>

        </div>
    </div>
    </div>




    